name: Deploy to Production

on:
  push:
    branches:
      - main

concurrency: production
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
